name: On Merge

on:
  push:
    branches:
      - master
      - development

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout alfred-python
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Build package
        run: make test && make build

  release:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: python
          token: ${{ secrets.PAT_TOKEN }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-python@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: "3.8"

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: make test && make build

      - name: Publish package
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
