name: On PR

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: tagshelfsrl/action-semantic-pull-request@main
        with:
          types: |
            chore
            docs
            fix
            feat
            misc
            test
            release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout alfred-python
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Build package
        run: make test && make build

