name: "On PR"

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    uses: tagshelfsrl/github-actions/.github/workflows/docker-build-push.yml@v1.11.1
    secrets:
      build-args: |
        PYPI_USER=${{ secrets.PYPI_USER }}
        PYPI_PASS=${{ secrets.PYPI_PASS }}
    with:
      images: |
        ${{ github.repository }}
